### ISSUE TITLE
error TS2339: Property 'object' does not exist on type 'Vine'

### ISSUE THREAD

**Issue by zulfikra96** [vinejs/vine#12]
### Package version

^1.5.2

### Describe the bug

Hi guys.
I face an issue that the typescript compiler can not find 'object'  on type Vine 

![vine-2](https://github.com/vinejs/vine/assets/11756770/64cc674f-0cfd-44cb-b2e2-d7017e991b2a)
![vine-3](https://github.com/vinejs/vine/assets/11756770/d0d77ee4-fde2-46f3-b156-2b9699299ae6)
![vine](https://github.com/vinejs/vine/assets/11756770/ce077c38-6121-4c5b-a999-1764c7a0184d)

import vine from "@vinejs/vine";
const schema: any = vine.object({
			is_active: vine.boolean()
		});
		const validator = vine.compile(schema);
		await validator.validate(data);

**Comment by Julien-R44** [comment]
looks strange. can you share your tsconfig.json or a repro repo please?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by akatora28** [comment]
Just ran into this issue as well in VS code, for me the issue was due to VS code using the built in Typescript version, instead of the installed one. To fix the issue, make sure that you select the Workspace Typescript version by hovering over the `{}` to the left of `TypeScript` in VS Code.
<img width="457" alt="Screenshot 2023-11-03 at 4 43 57 PM" src="https://github.com/vinejs/vine/assets/22596574/634df6cf-5bf7-44d4-a757-f783f0efe89f">
